# Generated by Django 3.0.1 on 2020-01-06 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number_1', models.CharField(max_length=100)),
                ('phone_number_2', models.CharField(max_length=100)),
                ('phone_number_3', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_img', imagekit.models.fields.ProcessedImageField(default='images/no-image-found.jpg', upload_to='images/')),
                ('sex', models.CharField(max_length=64)),
                ('race', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('castrated', models.BooleanField(default=False)),
                ('castration_date', models.DateField(blank=True, null=True)),
                ('aggressive', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('obs', models.TextField(blank=True, default='')),
                ('allergies', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Owner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
        migrations.CreateModel(
            name='DewormingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiparasitic_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('abstract', models.CharField(max_length=255)),
                ('history', models.TextField(blank=True, default='')),
                ('clinic_signs', models.TextField(blank=True, default='')),
                ('diagnosis', models.TextField(blank=True, default='')),
                ('treatments', models.TextField(blank=True, default='')),
                ('obs', models.TextField(blank=True, default='')),
                ('complementary_studies', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
    ]
