# Generated by Django 3.0.1 on 2019-12-27 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number_1', models.CharField(max_length=100)),
                ('phone_number_2', models.CharField(max_length=100)),
                ('phone_number_3', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_img', models.ImageField(blank=True, default='images/no-image-found.png', upload_to='images/')),
                ('sex', models.CharField(max_length=64)),
                ('race', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('castrated', models.BooleanField(default=False)),
                ('castration_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(default='')),
                ('obs', models.TextField(default='')),
                ('allergies', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
        migrations.CreateModel(
            name='DewormingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiparasitic_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('next_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_signs', models.CharField(max_length=255)),
                ('treatments', models.CharField(max_length=255)),
                ('obs', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
    ]
