# Generated by Django 3.0.1 on 2019-12-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petfile',
            old_name='petFile',
            new_name='owner_id',
        ),
    ]
