# Generated by Django 3.0.1 on 2020-01-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deworminghistory',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
