# Generated by Django 3.1.3 on 2021-01-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petfile',
            name='species',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
