# Generated by Django 3.0.1 on 2019-12-23 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='castration_date',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1111, 11, 11), null=True),
        ),
    ]
