# Generated by Django 3.0.1 on 2020-01-08 17:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_clinichistoryimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinichistoryimg',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
