# Generated by Django 3.0.1 on 2020-01-11 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200110_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternmentDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('clinic_signs', models.TextField(blank=True, default='')),
                ('treatment', models.CharField(max_length=255)),
                ('obs', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='clinichistoryimg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InternmentTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=255)),
                ('drug_hour', models.TimeField(blank=True, null=True)),
                ('be_notified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internmentDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.InternmentDay')),
            ],
        ),
        migrations.CreateModel(
            name='InternmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.PetFile')),
            ],
        ),
        migrations.CreateModel(
            name='InternmentDayImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internmentDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.InternmentDay')),
            ],
        ),
        migrations.AddField(
            model_name='internmentday',
            name='internmentHistory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.InternmentHistory'),
        ),
    ]
