# Generated by Django 3.0.1 on 2019-12-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20191227_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petfile',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
