# Generated by Django 3.0.1 on 2019-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20191223_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='castration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
