# Generated by Django 3.0.1 on 2019-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20191223_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='petfile',
            name='pet_img',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
