# Generated by Django 3.0.1 on 2020-01-11 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200111_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='internmenthistory',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='internmenthistory',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
