# Generated by Django 3.0.1 on 2020-01-10 13:15

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20200108_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinichistoryimg',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='vaccinationhistory',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
