# Generated by Django 3.0.1 on 2019-12-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20191227_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='petfile',
            name='aggressive',
            field=models.BooleanField(default=False),
        ),
    ]
