# Generated by Django 3.0.1 on 2020-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200111_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internmentday',
            name='treatment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
