# Generated by Django 3.0.1 on 2019-12-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_petfile_pet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='pet_img',
            field=models.ImageField(blank=True, default='images/no-image-found.jpg', upload_to='images/'),
        ),
    ]
