# Generated by Django 3.0.1 on 2019-12-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_petfile_aggressive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='petfile',
            options={'ordering': ['created_at']},
        ),
    ]
