# Generated by Django 3.0.1 on 2019-12-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20191224_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='pet_img',
            field=models.ImageField(blank=True, default='images/no-image-found.png', upload_to='images/'),
        ),
    ]
