# Generated by Django 3.0.1 on 2019-12-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20191228_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petfile',
            options={'ordering': ['pet_name']},
        ),
    ]
