# Generated by Django 3.0.1 on 2019-12-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20191228_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petfile',
            options={'ordering': ['created_at']},
        ),
    ]
