# Generated by Django 3.0.1 on 2020-01-04 12:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20191228_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='obs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='pet_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/no-image-found.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='petfile',
            name='race',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
