# Generated by Django 3.0.1 on 2020-01-04 12:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20200104_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='pet_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/no-image-found.jpg', upload_to='images/'),
        ),
    ]
