# Generated by Django 3.0.1 on 2020-01-04 12:58

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20200104_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfile',
            name='pet_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/no-image-found.png', upload_to='images/'),
        ),
    ]
