# Generated by Django 3.1.3 on 2021-02-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_productimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimg',
            old_name='Product',
            new_name='product',
        ),
    ]
